{
 "title": "Monitoramento",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "Servidor", "query": "db1, db2, db3" },
   { "name": "node_name", "query": "mysql" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Desempenho", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quantidade de conexões",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "employees",
     "rawSql": "SELECT \r\n    SUM(state = 'executing' OR command NOT IN ('Sleep', 'Binlog Dump', 'Connect')) AS active,\r\n    SUM(command = 'Sleep') AS sleep,\r\n    COUNT(*) AS total\r\nFROM performance_schema.processlist;\r\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg by (node_name) (clamp_max(sum by (node_name) ( avg by (mode,node_name) ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$server\",region=~\".*\",node_type=~\".*\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or \n(irate(node_cpu_seconds_total{node_name=~\"$server\",region=~\".*\",node_type=~\".*\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[5m])) )*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$server\",region=~\".*\",node_type=~\".*\", mode=~\"total\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$server\",region=~\".*\",node_type=~\".*\", mode=~\"total\"}[5m]) or avg_over_time(node_cpu_average{node_name=~\"$server\",region=~\".*\",node_type=~\".*\",node_type=\"remote_azure_database\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$server\",region=~\".*\",node_type=~\".*\",node_type=\"remote_azure_database\"}[5m]))),100))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Free Memory Percent",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name) ((((max_over_time(node_memory_MemAvailable_bytes{node_name=~\"$server\"}[$interval]) or\nmax_over_time(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"}[5m])) or\n(node_memory_MemFree_bytes{node_name=~\"$server\"} + \nnode_memory_Buffers_bytes{node_name=~\"$server\"} + \nnode_memory_Cached_bytes{node_name=~\"$server\"})) /\n(max_over_time(node_memory_MemTotal_bytes{node_name=~\"$server\"}[$interval]) or \nmax_over_time(node_memory_MemTotal_bytes{node_name=~\"$server\"}[$interval])))),1)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg by (node_name) (100 - azure_memory_percent_average{node_name=~\"$server\"})/100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Consultas ativas",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "employees",
     "rawSql": "SELECT \r\n    TIME AS `Tempo em Execução`,\r\n    TIME_FORMAT(from_unixtime(UNIX_TIMESTAMP(NOW()) - TIME), '%H:%i:%s') AS `Início Query`,\r\n    IFNULL(DB, '') AS `Database`,\r\n    HOST AS `IP Usuário`,\r\n    USER AS `Usuário`,\r\n    INFO AS `Query`\r\nFROM performance_schema.processlist\r\nWHERE COMMAND NOT IN ('Sleep', 'Connect')\r\n  AND INFO IS NOT NULL  \r\nORDER BY TIME DESC;"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "employees",
     "rawSql": "SELECT\r\n    rdl.OBJECT_SCHEMA AS waiting_schema,\r\n    rdl.OBJECT_NAME AS waiting_table,\r\n    rdl.INDEX_NAME AS waiting_index,\r\n    rdl.LOCK_TYPE AS waiting_lock_type,\r\n    rdl.LOCK_MODE AS waiting_lock_mode,\r\n    rdl.LOCK_DATA AS waiting_row,\r\n    wt.PROCESSLIST_ID AS waiting_process_id,\r\n    wt.PROCESSLIST_USER AS waiting_user,\r\n    wt.PROCESSLIST_HOST AS waiting_host,\r\n    wt.PROCESSLIST_INFO AS waiting_query,\r\n    bdl.OBJECT_SCHEMA AS blocking_schema,\r\n    bdl.OBJECT_NAME AS blocking_table,\r\n    bdl.INDEX_NAME AS blocking_index,\r\n    bdl.LOCK_TYPE AS blocking_lock_type,\r\n    bdl.LOCK_MODE AS blocking_lock_mode,\r\n    bdl.LOCK_DATA AS blocking_row,\r\n    bt.PROCESSLIST_ID AS blocking_process_id,\r\n    bt.PROCESSLIST_USER AS blocking_user,\r\n    bt.PROCESSLIST_HOST AS blocking_host,\r\n    bt.PROCESSLIST_INFO AS blocking_query\r\nFROM\r\n    performance_schema.data_lock_waits dw\r\n    JOIN performance_schema.data_locks rdl ON dw.REQUESTING_ENGINE_LOCK_ID = rdl.ENGINE_LOCK_ID\r\n    JOIN performance_schema.data_locks bdl ON dw.BLOCKING_ENGINE_LOCK_ID = bdl.ENGINE_LOCK_ID\r\n    JOIN performance_schema.threads wt ON rdl.THREAD_ID = wt.THREAD_ID\r\n    JOIN performance_schema.threads bt ON bdl.THREAD_ID = bt.THREAD_ID;\r\n"
    }
   ]
  },
  { "title": "Replicação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Replication Group Members",
   "type": "table",
   "description": "This table shows network and status information for replication group members. The network addresses shown are the addresses used to connect clients to the group, and should not be confused with the member's internal group communication address specified by group_replication_local_address.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "mysql_perf_schema_replication_group_member_info{node_name=~\"$server\"} or mysql_perf_schema_replication_group_5_member_info{node_name=~\"$server\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}